<?php

namespace echolibre\google_wave\Events;

const WAVELET_BLIP_CREATED = 'WAVELET_BLIP_CREATED'
const WAVELET_BLIP_REMOVED = 'WAVELET_BLIP_REMOVED'
const WAVELET_PARTICIPANTS_CHANGED = 'WAVELET_PARTICIPANTS_CHANGED'
const WAVELET_SELF_ADDED = 'WAVELET_SELF_ADDED'
const WAVELET_SELF_REMOVED = 'WAVELET_SELF_REMOVED'
const WAVELET_TIMESTAMP_CHANGED = 'WAVELET_TIMESTAMP_CHANGED'
const WAVELET_TITLE_CHANGED = 'WAVELET_TITLE_CHANGED'
const WAVELET_VERSION_CHANGED = 'WAVELET_VERSION_CHANGED'
const BLIP_CONTRIBUTORS_CHANGED = 'BLIP_CONTRIBUTORS_CHANGED'
const BLIP_DELETED = 'BLIP_DELETED'
const BLIP_SUBMITTED = 'BLIP_SUBMITTED'
const BLIP_TIMESTAMP_CHANGED = 'BLIP_TIMESTAMP_CHANGED'
const BLIP_VERSION_CHANGED = 'BLIP_VERSION_CHANGED'
const DOCUMENT_CHANGED = 'DOCUMENT_CHANGED'
const FORM_BUTTON_CLICKED = 'FORM_BUTTON_CLICKED'
