<?php

namespace echolibre\google_wave\Operations;

const WAVELET_APPEND_BLIP = 'WAVELET_APPEND_BLIP';
const WAVELET_ADD_PARTICIPANT = 'WAVELET_ADD_PARTICIPANT';
const WAVELET_CREATE = 'WAVELET_CREATE';
const WAVELET_REMOVE_SELF = 'WAVELET_REMOVE_SELF';
const WAVELET_DATADOC_SET = 'WAVELET_DATADOC_SET';
const WAVELET_SET_TITLE = 'WAVELET_SET_TITLE';
const BLIP_CREATE_CHILD = 'BLIP_CREATE_CHILD';
const BLIP_DELETE = 'BLIP_DELETE';
const DOCUMENT_ANNOTATION_DELETE = 'DOCUMENT_ANNOTATION_DELETE';
const DOCUMENT_ANNOTATION_SET = 'DOCUMENT_ANNOTATION_SET';
const DOCUMENT_ANNOTATION_SET_NORANGE = 'DOCUMENT_ANNOTATION_SET_NORANGE';
const DOCUMENT_APPEND = 'DOCUMENT_APPEND';
const DOCUMENT_APPEND_STYLED_TEXT = 'DOCUMENT_APPEND_STYLED_TEXT';
const DOCUMENT_INSERT = 'DOCUMENT_INSERT';
const DOCUMENT_DELETE = 'DOCUMENT_DELETE';
const DOCUMENT_REPLACE = 'DOCUMENT_REPLACE';
const DOCUMENT_ELEMENT_APPEND = 'DOCUMENT_ELEMENT_APPEND';
const DOCUMENT_ELEMENT_DELETE = 'DOCUMENT_ELEMENT_DELETE';
const DOCUMENT_ELEMENT_INSERT = 'DOCUMENT_ELEMENT_INSERT';
const DOCUMENT_ELEMENT_INSERT_AFTER = 'DOCUMENT_ELEMENT_INSERT_AFTER';
const DOCUMENT_ELEMENT_INSERT_BEFORE = 'DOCUMENT_ELEMENT_INSERT_BEFORE';
const DOCUMENT_ELEMENT_REPLACE = 'DOCUMENT_ELEMENT_REPLACE';
const DOCUMENT_INLINE_BLIP_APPEND = 'DOCUMENT_INLINE_BLIP_APPEND';
const DOCUMENT_INLINE_BLIP_DELETE = 'DOCUMENT_INLINE_BLIP_DELETE';
const DOCUMENT_INLINE_BLIP_INSERT = 'DOCUMENT_INLINE_BLIP_INSERT';
const DOCUMENT_INLINE_BLIP_INSERT_AFTER_ELEMENT = 'DOCUMENT_INLINE_BLIP_INSERT_AFTER_ELEMENT';

class AbstractOperation {}
